--
--
--
INSERT INTO CTG_BRANDS(CTGBRD_ID,CTGBRD_NAME) VALUES( 1, 'BRAND 1');
--
--
--
INSERT INTO CTG_TYPES(CTGTYP_ID,CTGTYP_NAME) VALUES( 1, 'TYPE 1');
--
--
--
INSERT INTO CTG_ITEMS(CTGITM_ID,CTGITM_CATID,CTGITM_BRDID,CTGITM_DESCRIPTION,CTGITM_NAME,CTGITM_PRICE,CTGITM_IMG,CTGITM_AVLSTK,CTGITM_STKSTATUS) VALUES( 1, 1,1,'DESCRIPTION','NAME1',100.00,'IMG1.PNG',10,0);