--
--CTG_BRANDS
--
DROP TABLE IF EXISTS CTG_BRANDS;
CREATE TABLE CTG_BRANDS( 
	CTGBRD_ID	BIGINT 		AUTO_INCREMENT  PRIMARY KEY,
	CTGBRD_NAME	VARCHAR(50) NOT NULL
);
--
--CTG_TYPES
--
DROP TABLE IF EXISTS CTG_TYPES;
CREATE TABLE CTG_TYPES( 
	CTGTYP_ID	BIGINT 		AUTO_INCREMENT  PRIMARY KEY,
	CTGTYP_NAME	VARCHAR(50) NOT NULL
);
--
--CTG_ITEMS
--
DROP TABLE IF EXISTS CTG_ITEMS;
CREATE TABLE CTG_ITEMS( 
	CTGITM_ID			BIGINT 			AUTO_INCREMENT  PRIMARY KEY,
	CTGITM_CATID		BIGINT 			NOT NULL,
	CTGITM_BRDID		BIGINT 			NOT NULL,
	CTGITM_DESCRIPTION	VARCHAR(35) 	NULL,
	CTGITM_NAME			VARCHAR(50) 	NOT NULL,
	CTGITM_PRICE		DECIMAL(14,2) 	NOT NULL,
	CTGITM_IMG			VARCHAR(25) 	NULL,
	CTGITM_AVLSTK		BIGINT			NOT NULL,
	CTGITM_STKSTATUS	INT				NOT NULL
);
